### ISSUE TITLE
Chart Uploader: java.lang.NullPointerException

### ISSUE THREAD

**Issue by ph1l** [SignalK/signalk-java#11]
Attempting to upload charts fails with no user feedback via web interface. I've attempted selecting one file or multiple zip files generated by freeboard-installer.

logs follow:

```
19:42:05.909 [qtp6313372-4228 - /signalk/v1/upload] ERROR nz.co.fortytwo.signalk.processor.UploadProcessor - null
java.lang.NullPointerException
        at nz.co.fortytwo.signalk.processor.UploadProcessor.install(UploadProcessor.java:167) [signalk-server-java-JIT-Deploy-30.jar:?]
        at nz.co.fortytwo.signalk.processor.UploadProcessor.processUpload(UploadProcessor.java:138) [signalk-server-java-JIT-Deploy-30.jar:?]
        at nz.co.fortytwo.signalk.processor.UploadProcessor.process(UploadProcessor.java:101) [signalk-server-java-JIT-Deploy-30.jar:?]
        at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63) [camel-core-2.15.2.jar:2.15.2]
        at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77) [camel-core-2.15.2.jar:2.15.2]
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:448) [camel-core-2.15.2.jar:2.15.2]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) [camel-core-2.15.2.jar:2.15.2]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:118) [camel-core-2.15.2.jar:2.15.2]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) [camel-core-2.15.2.jar:2.15.2]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) [camel-core-2.15.2.jar:2.15.2]
        at org.apache.camel.component.jetty.CamelContinuationServlet.service(CamelContinuationServlet.java:162) [camel-jetty-common-2.15.2.jar:2.15.2]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:668) [geronimo-servlet_3.0_spec-1.0.jar:1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:229) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.server.handler.ResourceHandler.handle(ResourceHandler.java:386) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.server.Server.handle(Server.java:366) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-all-8.1.16.v20140903.jar:8.1.16.v20140903]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
```

**Comment by rob42** [comment]
Ive seen this before, its looking for the `Metadata.scale` entry in `tilemapresource.xml`
This is used to layer the charts so most detail goes on top. 

Can you confirm you used the latest freeboard-installer pls? The early ones didnt have this.
Also some details on the KAP file you processed.

**Comment by ph1l** [comment]
These were ZIP files I built with freboard-installer last year and used successfully with the original freeboard project. I'll attempt to re-convert them and try again.

**Comment by ph1l** [comment]
re-converted: NOAA RNC (KAP) http://www.charts.noaa.gov/RNCs/Agreement.shtml?18652

It seems to be uploading the files now.
